services:
  - type: web
    name: gateway-api
    runtime: node
    plan: free
    region: ohio
    buildCommand: npm install
    startCommand: npm start
    rootDir: ./gateway-api
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: USERS_API_URL
        value: https://users-api-jmp5.onrender.com
      - key: APPOINTMENTS_API_URL
        value: https://carwash-appointments.onrender.com
      - key: SERVICES_API_URL
        value: https://carwash-services.onrender.com
      - key: FRONTEND_URL
        value: https://carwashfrontend.netlify.app
    healthCheckPath: /